import hashlib

import pytest

from creative_workflow.server.services.artifacts import ArtifactService
from creative_workflow.shared.contracts.assets import AssetUploadMetadata
from creative_workflow.shared.enums import AssetClass, RetentionClass, SourceService


def test_artifact_service_sanitizes_filename_and_verifies_checksum(db_session, server_settings):
    data = b"real generated bytes"
    metadata = AssetUploadMetadata(
        task_id="task_1",
        run_id="run_1",
        job_id="job_1",
        asset_class=AssetClass.GENERATED,
        retention_class=RetentionClass.TTL_30D,
        original_filename="../hero image.png",
        content_type="image/png",
        size_bytes=len(data),
        sha256=hashlib.sha256(data).hexdigest(),
        source_service=SourceService.FREEPIK,
    )
    asset = ArtifactService(db_session, server_settings).store_upload(metadata, data)

    assert ".." not in asset.relative_path
    assert asset.relative_path.startswith("tasks/task_1/generated/")
    assert (server_settings.artifact_root / asset.relative_path).exists()


def test_artifact_service_rejects_checksum_mismatch(db_session, server_settings):
    metadata = AssetUploadMetadata(
        task_id="task_1",
        asset_class=AssetClass.DEBUG,
        retention_class=RetentionClass.DEBUG_TTL_7D,
        original_filename="trace.txt",
        content_type="text/plain",
        size_bytes=3,
        sha256="0" * 64,
        source_service=SourceService.GEMINI,
    )
    with pytest.raises(ValueError, match="sha256 mismatch"):
        ArtifactService(db_session, server_settings).store_upload(metadata, b"abc")

